name: Build and Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        working-directory: Lambda-Authenticator/Lambda-Authenticator # Diretório correto do projeto
        run: dotnet restore

      - name: Build and package Lambda
        working-directory: Lambda-Authenticator/Lambda-Authenticator # Diretório correto do projeto
        run: dotnet lambda package -c Release -o Lambda-Authenticator.zip

      - name: Deploy Lambda to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ env.REGION_DEFAULT }}
        working-directory: Lambda-Authenticator/Lambda-Authenticator # Diretório onde o pacote foi gerado
        run: |
          aws lambda update-function-code --function-name CustomAuthorizerLambda --zip-file fileb://Lambda-Authenticator.zip
