name: Build and Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' 

      - name: Install dependencies
        run: dotnet restore

      - name: Build and package Lambda
        run: dotnet lambda package -c Release -o Lambda-Authenticator.zip

      - name: Deploy Lambda to AWS
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}
        run: |
          aws lambda update-function-code --function-name CustomAuthorizerLambda --zip-file fileb://Lambda-Authenticator.zip
